version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "8:30"
    open-pull-requests-limit: 10
    reviewers:
      - "erik-berndt"
    assignees:
      - "erik-berndt"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-patch"
        minor-updates:
          patterns:
            - "*"
          update-types:
            - "version-update:semver-minor"
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]